### PR TITLE
Feat/add rules for arbitrary values for (max/min-)width/height

### PR DESCRIPTION
**Pull request by AnnaRybkina**
### Description
This PR adds support for arbitrary values for (max/min-)width/height classes.
Examples:
- `min-w-[400]`, 
- `min-w-[40rem]`,
- `max-h-[400]`, 
- `max-h-[400px]`,
- `w-[70]`, 
- `h-[70]`,
- `h-[70px]`,
- `h-[7rem]`

The number values default to `rem` but we also support generating values in `px` based on`theme.usePixels` boolean.

### Required action:
- [x] - [Update documentation](https://warp-ds.github.io/css-docs/max-height#arbitrary-values)

### CODE REVIEW

**Comment by AnnaRybkina** [comment]
[Engine: Add support for arbitrary values for max/min-height/width:](https://trello.com/c/yuOb2aSm/78-engine-add-support-for-arbitrary-values-for-max-min-height-width)

**Comment by AnnaRybkina** [comment]
[Add support for arbitrary values for height and width.  h-[  ], and w-[  ]](https://trello.com/c/f0GNpAXU/75-add-support-for-arbitrary-values-for-height-and-width-h-and-w)

**Review by Skadefryd — APPROVED** [review]
Looks good to me :)  Good job!

**Comment by BalbinaK** [comment]
Added support for rem/px units as part of arbitrary values in [8e71d2c](https://github.com/warp-ds/drive/pull/47/commits/8e71d2cf9dedd054c278b7a89f369334a5ba1c51).

**Pull request merged**
