### PR TITLE
docs: first step to Typescript version of this project

### PR DESCRIPTION
**Pull request by eshimischi**
I find it pretty important to rewrite this preset into Typescript. Example: [Scalpel](https://github.com/macheteHot/unocss-preset-scalpel)

This pull request is the first step.

### CODE REVIEW

**Comment by AnnaRybkina** [comment]
Great suggestion 🙌 We do not have TS migration on our nearest road map yet. But will take your suggestion into consideration and will create an issue and fix it if it will be applicable for our preset.

**Comment by eshimischi** [comment]
> Great suggestion 🙌 We do not have TS migration on our nearest road map yet. But will take your suggestion into consideration and will create an issue and fix it if it will be applicable for our preset.

I was searching for my time to do the migration by myself, okay let's close this pull for now. As fas as i finish it, i'll create a new one. This whole thing isn't my only challenge, TS is just must in terms of any JS project now.

**Comment by eshimischi** [comment]
At least it is possible to generate d.ts using tools like Microsoft Api Extractor for IDEs and proper work in TS project like mine. Thanks!

**Comment by eshimischi** [comment]
Screenshot 2023-06-13 at 23 43 55

**Pull request closed without merging**
